* lein-droid

  [[https://travis-ci.org/clojure-android/lein-droid/][https://travis-ci.org/clojure-android/lein-droid.svg?branch=master]]

  A Leiningen plugin to simplify Clojure development for Android
  platform. It acts as a build-tool for Clojure/Android projects.

** Usage

   First make sure you have [[http://developer.android.com/sdk/index.html][Android SDK]] installed, with the latest
   Android SDK Build-tools and Android Support Repository.

   Follow the [[https://github.com/clojure-android/lein-droid/wiki/Tutorial][Tutorial]] to start using lein-droid.

   Latest release:

[[https://clojars.org/lein-droid][https://clojars.org/lein-droid/latest-version.svg]]

** Documentation

   The [[https://github.com/clojure-android/lein-droid/wiki][wiki]] is a primary source of lein-droid documentation. To know more about
   =project.clj= options lein-droid supports, consult [[https://github.com/clojure-android/lein-droid/wiki/project.clj-options][this page]].

   If you'd like to read the code, Marginalia docs are [[http://clojure-android.github.io/lein-droid/][here]].

   [[https://github.com/krisc][Kris Calabio]] wrote a [[https://github.com/alexander-yakushev/events/blob/master/tutorial.md][tutorial]] on how to write your first real Clojure/Android
   application.

** How to modify lein-droid

   Being a plugin for Leiningen, the workflow for modifying, debugging and
   testing it is slightly more complicated than with a regular Clojure project.
   See [[https://github.com/clojure-android/lein-droid/wiki/Hacking-the-plugin][Hacking the plugin]] page for details.

** Contributors

   I thank the following people for their help in extending and
   improving lein-droid:

   - [[https://github.com/AdamClements][Adam Clements]]
   - [[https://github.com/oakes][Zach Oakes]]
   - [[https://github.com/ayamada][Atsuo Yamada]]
   - [[https://github.com/sergv][Sergey Vinokurov]]
   - [[https://github.com/clojure-android/lein-droid/graphs/contributors][and others]]

** License

   Copyright © 2012-2015 Alexander Yakushev. Distributed under the Eclipse
   Public License, the same as Clojure. See the file [[https://github.com/clojure-android/lein-droid/blob/master/COPYING][COPYING]].
